### ISSUE TITLE
Handle promise rejections for future Node releases

### ISSUE THREAD

**Issue by niamurrell** [niamurrell/value-app#13]
### Expected Behavior

No warnings in the console when running the app.

### Actual Behavior

Warning is given:

```sh
(node:30405) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:30405) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

(node:30405) DeprecationWarning: collection.findAndModify is deprecated. Use findOneAndUpdate, findOneAndReplace or findOneAndDelete instead.
```

Note it's just a warning, the app still runs for now.

### Feature Request/Idea

[Here](https://medium.com/dailyjs/how-to-prevent-your-node-js-process-from-crashing-5d40247b8ab2) is a starter on fixing this issue.

### Steps to Reproduce (including precondition)

Run the app and do any action where data is saved/updated.

**Comment by anacoimbrag** [comment]
Hey! Is this problem still going? I`d like to help you solve it, but I cannot reproduce this here.
