### ISSUE TITLE
Clicking delete icon doesn't open delete modal

### ISSUE THREAD

**Issue by niamurrell** [niamurrell/value-app#15]
### Expected Behavior

Clicking the **delete** icon next to a date will open the modal to delete that date.

### Actual Behavior

Nothing happens on the first click. The modal opens on the 2nd click.

### Feature Request/Idea

n/a

### Steps to Reproduce (including precondition)

1. Must have a 'thing' available in your account
2. The 'thing' must have been used at least once
3. Click the delete icon next to a usage date

### Your Environment

- OS: Mac
- browser + version: Chrome, Brave

**Comment by dongido001** [comment]
Can I take this one?

**Comment by niamurrell** [comment]
Go for it @dongido001, thanks!

**Comment by dongido001** [comment]
PR submitted @niamurrell - #17
