### ISSUE TITLE
Improve UX - add a 'use today' button to thing cards

### ISSUE THREAD

**Issue by niamurrell** [niamurrell/value-app#16]
### Expected Behavior

You can add a usage to today by clicking once from the list of mythings

### Actual Behavior

You have to open the thing, and then click to add a use, then select today's date, *then* confirm.

### Feature Request/Idea

Add a second button to the card to shorten the process.

**Comment by Djdany95** [comment]
Opened PR 😄

**Comment by niamurrell** [comment]
Reduced from 4 clicks to 2.
