### ISSUE TITLE
Home button is useless

### ISSUE THREAD

**Issue by Djdany95** [niamurrell/value-app#20]
The header home button does exactly the same as the logo button and there are another in the footer.

### Expected Behavior

Just one button to go home.

### Actual Behavior

There are 2 buttons to go home.

### Feature Request/Idea

Remove home button for clear UI.

**Comment by Djdany95** [comment]
Opened PR 😄

**Comment by cziem** [comment]
Can I take this ?

**Comment by niamurrell** [comment]
@phavor There is an open PR for this one

**Comment by cziem** [comment]
Okay. Let me search for another

**Comment by niamurrell** [comment]
Thanks @djdany01! Merged in #23
