### ISSUE TITLE
Add GitHub repo link to UI

### ISSUE THREAD

**Issue by niamurrell** [niamurrell/value-app#31]
### Expected Behavior

Site visitors can see a link that says **Contribute** with the GitHub icon. They can click the link to go to the repo. The link is inconspicuous in a corner of the page.

### Actual Behavior

Reference to contributing does not exist except in the console as an easter egg.

**Comment by juliofortunato** [comment]
Hey, can I work on this issue?
Do you have a specific design in mind for this?

**Comment by niamurrell** [comment]
@juliofortunato Sure go for it! Here are some pages along the lines of what I had in mind:

* [would say 'contribute' instead of 'fork me on GH'](http://shannoncrabill.com/how-many-days-until-halloween/)
* [graphic version works too](http://tholman.com/github-corners/)

Because the nav bar stacks on small-width screens, it may work best in the bottom right of the page as part of the footer. The height of the footer may need to be increased. Otherwise happy for you to create a design that you think fits well with the rest of the site.

Thanks for giving it a go 👍

**Comment by juliofortunato** [comment]
@niamurrell just submited the PR (#33)
