### ISSUE TITLE
Fix footer scroll clearance in mobile view

### ISSUE THREAD

**Issue by niamurrell** [niamurrell/value-app#8]
When viewing the site on a mobile device, the footer covers the bottom content on the page.

**Comment by pfistersimon** [comment]
can i work on it

**Comment by niamurrell** [comment]
@pfistersimon Go for it, thanks!

**Comment by louierosero** [comment]
Can I fixed this?

**Comment by niamurrell** [comment]
Closing as implemented.

@pfistersimon if you're still working on this feel free to submit a pull request, maybe you'll have a different fix
